// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyDvc6-fcdeVDmNpt_Q9bTlMu1wkYLvzo',
    appId: '1:409323017729:web:8bbbafd6590c34e348d200',
    messagingSenderId: '409323017729',
    projectId: 'uas-21312087',
    authDomain: 'uas-21312087.firebaseapp.com',
    storageBucket: 'uas-21312087.appspot.com',
    measurementId: 'G-RD5LD7JJBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx7-_qBNJ8ee9_I_Nq8EUXTyRuS8Mi7PY',
    appId: '1:409323017729:android:9ddd53aa66dce1e548d200',
    messagingSenderId: '409323017729',
    projectId: 'uas-21312087',
    storageBucket: 'uas-21312087.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASZbULJzV4wjn3HOgtcQF9Tf2AuLS1ip8',
    appId: '1:409323017729:ios:8db659575ca36e5848d200',
    messagingSenderId: '409323017729',
    projectId: 'uas-21312087',
    storageBucket: 'uas-21312087.appspot.com',
    iosBundleId: 'com.ifgabsp.projectGet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASZbULJzV4wjn3HOgtcQF9Tf2AuLS1ip8',
    appId: '1:409323017729:ios:dc2e4cca0b17dcb848d200',
    messagingSenderId: '409323017729',
    projectId: 'uas-21312087',
    storageBucket: 'uas-21312087.appspot.com',
    iosBundleId: 'com.ifgabsp.projectGet.RunnerTests',
  );
}
